name: CI - Build, Lint, Test

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: task-manager-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm         # keep cache, but do NOT require lockfile path

      - name: Install dependencies
        run: npm ci

      - name: Lint backend
        run: npm run lint --if-present

      - name: Run backend tests
        run: npm test --if-present

      - name: Build backend Docker image
        run: docker build -t task-manager-backend:ci .

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: task-manager-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run lint --if-present

      - name: Run frontend tests
        run: npm test --if-present

      - name: Build frontend Docker image
        run: docker build -t task-manager-frontend:ci .
